name: modeling_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - opencv
  - pip
  - setuptools
  - wheel
  - hdf5
  - eigen
  - packaging
  - pillow
  - jinja2
  - markupsafe
  - mpmath
  - networkx
  - sympy
  - filelock
  - fsspec
  - readline
  - sqlite
  - tk
  - zlib
  - lz4-c
  - bzip2
  - xz
  - ca-certificates
  - openssl
  - fontconfig
  - freetype
  - libpng
  - libtiff
  - libjpeg-turbo
  - pcre2
  - cairo
  - pango
  - harfbuzz
  - libxml2
  - gettext
  - leptonica
  - tesseract
  - pip:
      - torch
      - torchvision
      - typing-extensions
